{{- range .Values.services }}
{{- if .persistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-data
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .persistence.size }}
{{- end }}
{{- end }}
