{{- range concat .Values.services .Values.workers }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}-{{ .serviceAccount | default .name }}
  labels:
    app.kubernetes.io/part-of: {{ $.Release.Name }}
{{- end }}
